print ('Please input your name : ')
name = input()
print ('Please input your student ID : ')
SID = input()
print ('Please input your major : ')
major = input()

print('---------------------------' + '\n' + '    HANYANG UNIVERSITY' + '\n')
print('  NAME: ' + name)
print('  STUDENT ID: ' + SID)
print('  MAJOR: ' + major)
print('---------------------------')
